### ISSUE TITLE
Android Apk build 

### ISSUE THREAD

**Issue by tarmornpob** [artyom-beilis/OpenLiveStacker#108]
I want to know can i build new apk from your source code? *OpenLiveStacker Relase*

**Comment by tarmornpob** [comment]
Okay, i want to create app for only using libgphoto2 with android studio for wait_for_event capture and show only.
Can you suggest for me?/

Best Regards,

**Comment by artyom-beilis** [comment]
> Okay, i want to create app for only using libgphoto2 with android studio for wait_for_event capture and show only.
> Can you suggest for me?/
>
> Best Regards,

You mean something unrelated to Astro Photography? If so I suggest just build libgphoto - wrap relevant function it with Java/Kotlin and write your app. Because OpenLiveStacker is something different.

For building/using libgphoto on Android you can read here: https://github.com/gphoto/libgphoto2/pull/918 - it is my pool request that enabled Android support of libgphoto - you'll see some API details

**Comment by tarmornpob** [comment]
so i got  .so can be tutorial for using .so I test by using loadLibrary .so is not work, can you suggest video youtube
