### ISSUE TITLE
Streaming problem

### ISSUE THREAD

**Issue by han-k59** [artyom-beilis/OpenLiveStacker#21]
S7 phone:

Streaming start to work in bin4x4. So in format 1164x860  At higher resolution it does not work.

Stacking works at bin 2x2 so 2328 x1760. Even with debug on. Is stacking less CPU load then streaming? 

Streaming and stacking sometimes stop or do not start. A little frustrating. Maybe CPU overload? It would be better if it keeps on running.

**Comment by artyom-beilis** [comment]
Ok.. I'll try to reduce internal frame-rate or make it adaptable.

I need to stream images even if no new image arrived since actual image shown can have 2-3 frames delay.

**Comment by han-k59** [comment]
Why would you refresh the screen if no new image has arrived? Anyhow it would be better if it can work with low end phones. Saves also battery power. I noted that the battery can drain quickly. Users could be in the field without an electrical socket nearby. Secondly charging is not possible when the camera is connected.

**Comment by artyom-beilis** [comment]
> Why would you refresh the screen if no new image has arrived? 

Good question. Because browsers do not always show last video frame arrived and it is horribly confusing.

You go change stretch settings and don't see change and then you change once again and suddenly you see the change that is opposite of what you did.

So I keep streaming at 10FPS - but I assume it maybe indeed too high for large frames. I'll change it to something more adaptive - like increase when new frame arrives and reduce to something like 1FPS when nothing happens.

Also you need to have some minimal FPS otherwise the client disconnects (I seen it in cases when there 5s exposure length or more)

I need to add measure to reduce load. But I still need to keep some streaming.

**Comment by artyom-beilis** [comment]
Can you please check beta10. I fixed several bugs that caused significant overload and I also fixed the high FPS where not needed.

**Comment by artyom-beilis** [comment]
Closed as per CN report
