### ISSUE TITLE
Feature. Save settings like exposure time and camera gain

### ISSUE THREAD

**Issue by han-k59** [artyom-beilis/OpenLiveStacker#6]
Feature request. Save settings like exposure time and camera gain. These value have be typed every time which is a little frustrating.

**Comment by han-k59** [comment]
It is cumbersome to enter it each time.  I also have the impression the required camera gain (139) is not set. The set button becomes dark but no confirmation is given. Saving the last settings would be much more convenient. Same with pixel size and focal length. entering it for 10th time in a row is frustrating. 

The default exposure time of 10 ms is too low. Something like 3 seconds default would be much better.  The download time of the 32 mbyte files is probably longer

**Comment by artyom-beilis** [comment]
>Same with pixel size and focal length. entering it for 10th time in a row is frustrating.

Totally agree with it! It is on my TODO list. Just didn't get there yet. But this is something I clearly need.

> I also have the impression the required camera gain (139) is not set. 

If error happens you get response. I checked it. So if the button grayed than it succeed.

I want to do presets so you can select exposure/gain and other parameters (and darks for it as well) and in one selection you set them all.

In everything related to hardware control I want to be explicit since it has effect on sequencing and other things.

So this stuff on the way and you are correct about it.

You listed for me most feature request I wanted myself `:-)`

In any case, a guy named Guy was expecting to join me on many UI improvements. He is actually frontend developer - unlike me who does JS only once in a while as hobby. I mostly C++, python, math, algorithms, deep learning, backed (see [cppcms](http://cppcms.com) ). But my frontend web development knowledge isn't as good as I would want it to be.

**Comment by artyom-beilis** [comment]
Plate solver settings are now saved in beta7
